import { LanguageOption } from './types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    professionalVoiceId: 'hi-IN-SwaraNeural',
    localVoiceId: 'hi-IN-MadhurNeural',
    region: 'Pan-India / North India',
  },
  {
    code: 'en',
    name: 'English (India)',
    nativeName: 'Indian English',
    flag: '🇮🇳',
    professionalVoiceId: 'en-IN-NeerjaNeural',
    localVoiceId: 'en-IN-PrabhatNeural',
    region: 'Pan-India',
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    flag: '🇮🇳',
    professionalVoiceId: 'pa-IN-GurpreetNeural',
    localVoiceId: 'pa-IN-OjasNeural',
    region: 'Punjab, Delhi, Haryana',
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    professionalVoiceId: 'mr-IN-AarohiNeural',
    localVoiceId: 'mr-IN-ManoharNeural',
    region: 'Maharashtra, Goa',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    professionalVoiceId: 'ta-IN-PallaviNeural',
    localVoiceId: 'ta-IN-ValluvarNeural',
    region: 'Tamil Nadu, Puducherry',
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    professionalVoiceId: 'te-IN-ShrutiNeural',
    localVoiceId: 'te-IN-MohanNeural',
    region: 'Andhra Pradesh, Telangana',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    professionalVoiceId: 'bn-IN-TanishaaNeural',
    localVoiceId: 'bn-IN-BashkarNeural',
    region: 'West Bengal, Tripura, Assam',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    flag: '🇮🇳',
    professionalVoiceId: 'gu-IN-DhwaniNeural',
    localVoiceId: 'gu-IN-NiranjanNeural',
    region: 'Gujarat, Daman & Diu',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    professionalVoiceId: 'kn-IN-SapnaNeural',
    localVoiceId: 'kn-IN-GaganNeural',
    region: 'Karnataka',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    professionalVoiceId: 'ml-IN-SobhanaNeural',
    localVoiceId: 'ml-IN-MidhunNeural',
    region: 'Kerala, Lakshadweep',
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    flag: '🇮🇳',
    professionalVoiceId: 'or-IN-SubhasiniNeural',
    localVoiceId: 'or-IN-SukantNeural',
    region: 'Odisha',
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    flag: '🇮🇳',
    professionalVoiceId: 'as-IN-YashicaNeural',
    localVoiceId: 'as-IN-PriyomNeural',
    region: 'Assam',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇮🇳',
    professionalVoiceId: 'ur-IN-GulNeural',
    localVoiceId: 'ur-IN-SalmanNeural',
    region: 'Jammu & Kashmir, Telangana, UP, Bihar',
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    flag: '🇮🇳',
    professionalVoiceId: 'sa-IN-RadhikaNeural',
    localVoiceId: 'sa-IN-AaravNeural',
    region: 'Classical / Pan-India',
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    flag: '🇮🇳',
    professionalVoiceId: 'ne-NP-HemkalaNeural',
    localVoiceId: 'ne-NP-SagarNeural',
    region: 'Sikkim, West Bengal (Darjeeling)',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    flag: '🇮🇳',
    professionalVoiceId: 'sd-IN-KareenaNeural',
    localVoiceId: 'sd-IN-DeepakNeural',
    region: 'Gujarat, Maharashtra, Rajasthan',
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    flag: '🇮🇳',
    professionalVoiceId: 'kok-IN-KavyaNeural',
    localVoiceId: 'kok-IN-GirishNeural',
    region: 'Goa, Karnataka, Maharashtra',
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    flag: '🇮🇳',
    professionalVoiceId: 'mai-IN-RenuNeural',
    localVoiceId: 'mai-IN-AnandNeural',
    region: 'Bihar, Jharkhand',
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر / कश्मीरी',
    flag: '🇮🇳',
    professionalVoiceId: 'ks-IN-ZeenatNeural',
    localVoiceId: 'ks-IN-IrfanNeural',
    region: 'Jammu & Kashmir',
  },
  {
    code: 'bho',
    name: 'Bhojpuri',
    nativeName: 'भोजपुरी',
    flag: '🇮🇳',
    professionalVoiceId: 'bho-IN-AnjaliNeural',
    localVoiceId: 'bho-IN-RaviNeural',
    region: 'Bihar, Eastern UP, Jharkhand',
  },
  {
    code: 'mwr',
    name: 'Marwari',
    nativeName: 'मारवाड़ी',
    flag: '🇮🇳',
    professionalVoiceId: 'mwr-IN-SunitaNeural',
    localVoiceId: 'mwr-IN-GopalNeural',
    region: 'Rajasthan, Gujarat',
  },
  {
    code: 'bgc',
    name: 'Haryanvi',
    nativeName: 'हरियाणवी',
    flag: '🇮🇳',
    professionalVoiceId: 'bgc-IN-PoojaNeural',
    localVoiceId: 'bgc-IN-VikramNeural',
    region: 'Haryana, Delhi NCR',
  },
  {
    code: 'hne',
    name: 'Chhattisgarhi',
    nativeName: 'छत्तीसगढ़ी',
    flag: '🇮🇳',
    professionalVoiceId: 'hne-IN-MamtaNeural',
    localVoiceId: 'hne-IN-DineshNeural',
    region: 'Chhattisgarh',
  },
  {
    code: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    flag: '🇮🇳',
    professionalVoiceId: 'doi-IN-PreetiNeural',
    localVoiceId: 'doi-IN-RomeshNeural',
    region: 'Jammu & Kashmir, Himachal Pradesh',
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    flag: '🇮🇳',
    professionalVoiceId: 'sat-IN-ParbatiNeural',
    localVoiceId: 'sat-IN-ChikuNeural',
    region: 'Jharkhand, Odisha, West Bengal',
  },
  {
    code: 'mni',
    name: 'Manipuri (Meitei)',
    nativeName: 'মৈতৈলোন্',
    flag: '🇮🇳',
    professionalVoiceId: 'mni-IN-LinthoingambiNeural',
    localVoiceId: 'mni-IN-ChaobaNeural',
    region: 'Manipur',
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बड़ो',
    flag: '🇮🇳',
    professionalVoiceId: 'brx-IN-MainaoNeural',
    localVoiceId: 'brx-IN-BirenNeural',
    region: 'Assam, Bodoland',
  },
  {
    code: 'gbm',
    name: 'Garhwali',
    nativeName: 'गढ़वाली',
    flag: '🇮🇳',
    professionalVoiceId: 'gbm-IN-KalpanaNeural',
    localVoiceId: 'gbm-IN-NaveenNeural',
    region: 'Uttarakhand (Garhwal)',
  },
  {
    code: 'kfy',
    name: 'Kumaoni',
    nativeName: 'कुमाऊँनी',
    flag: '🇮🇳',
    professionalVoiceId: 'kfy-IN-ShardaNeural',
    localVoiceId: 'kfy-IN-KailashNeural',
    region: 'Uttarakhand (Kumaon)',
  },
  {
    code: 'raj',
    name: 'Rajasthani',
    nativeName: 'राजस्थानी',
    flag: '🇮🇳',
    professionalVoiceId: 'raj-IN-MeenaNeural',
    localVoiceId: 'raj-IN-ShyamNeural',
    region: 'Rajasthan',
  },
  {
    code: 'tcy',
    name: 'Tulu',
    nativeName: 'ತುಳು',
    flag: '🇮🇳',
    professionalVoiceId: 'tcy-IN-ShwethaNeural',
    localVoiceId: 'tcy-IN-ShekharNeural',
    region: 'Karnataka (Dakshina Kannada), Kerala',
  },
  {
    code: 'hi-en',
    name: 'Hinglish (Colloquial)',
    nativeName: 'Hinglish Mix',
    flag: '🇮🇳',
    professionalVoiceId: 'hi-IN-SwaraNeural',
    localVoiceId: 'en-IN-PrabhatNeural',
    region: 'Metro Cities & Urban India',
  },
];
